spring:
  cloud:
    gateway:
        httpserver:
            wiretap: true
        httpclient:
            wiretap: true

logging.level.com.example: DEBUG

app:
  services:
    # Refer to ServiceFilterConfiguration for more details
    routes:
  rewrites:
    # The keys under paths should match up with the ID of the filter.
    # Refer to RewriteConfiguration for more details
    paths: